@startuml
skinparam monochrome true
title "PSSM staff fullfilment Staffing Request"\nState Machine\n

[*] --> Opened : Created Outstanding \nStaffing Request
Opened --> InProgress: PSSM employee reviewing it
InProgress --> Fulfilled: Temp Employee Agree
InProgress --> NotPossible: No Temp Employee Found
Fulfilled --> Closed : Contract Manager closes Request
NotPossible --> Closed : Contract Manager closes Request
Closed --> [*]

@enduml
