@startuml
skinparam monochrome true
title PSSM Staffing Request\nState Machine\n

state StaffingRequest {
  [*] --> Opened : Created Outstanding \nStaffing Request
  Opened --> InProgress: PSSM\n Employee review
  InProgress --> Fulfilled: TempEmployee\nAgrees
  InProgress --> NotPossible: TempEmployee\nNot Found
  Fulfilled --> Closed : Contract Manager \ncloses Request
  NotPossible --> Closed : Contract Manager \ncloses Request
  Closed --> [*]
}

@enduml
