@startuml
skinparam monochrome true
title PSSM Temporary Staff Fullfilment\nSequence Diagram\n

actor Client as C
actor "Contract\nManager" as CM
actor "Temporary\nEmployee" as TE
actor "PSSM\nEmployee" as PE


participant ":Contract" as CO
participant ":Staffing\nRequest" as SR
participant ":Temp\nEmployee" as TEC


group Client Demand
  C -> CM : Request Temp Staff
  CM -> CO: validateContract()
  group Invalid StaffingRequest
    CO --> CM : Invalid Contract
    CM --> C : "unable-to-fill", Why Letter
  end
  CO --> CM : Valid Contract
  CM -> SR : createNewStaffingRequest()
end

group Placement
  PE -> SR : getStaffingRequest()
  SR --> PE : StaffingRequest
  PE -> TEC : getCandidates(StaffingRequest)
  group No Qualified Candidate Found
    TEC -> PE : No Candidate Found
    PE -> PE : Create "unable-to-fill" Memo
    PE -> SR : attachMemo()
    SR --> CM : Contract Manager notification
    CM -> CO : closeStaffingRequest()
  end
  TEC --> PE : Display Candidates
  PE -> TEC : reserveEmployee(StaffingRequest)
  TEC --> PE : Employee Reserved
  PE -> TE : Negotiate Placement
  group No Placement
    TE --> PE : Placement Not Agreed
    PE -> CO : fileContract(SR, bill, memo)
    CO --> CM : Contract Manager notification
    CM -> C : Client Notification, "unable-to-fill"
  end
  TE --> PE : Placement Agreed
  PE -> SR : updateStaffingRequest(TempEmployee)
  SR --> PE : StaffingRequest Updated
end

group Arrangement
  PE -> TEC : placeEmployee(StaffingRequest)
  TEC --> PE : Employee Placed
  CM -> SR : closeStaffingRequest()
  SR --> CM : Confirmation Message
  CM --> C: Notify Client, Request Filled
end

@enduml
