@startuml
skinparam monochrome true
title PSSM Staffing Request\nState Machine\n
state StaffingRequest {
  [*] --> New : Created \nStaffing Request
  New --> Opened : Contract Manager Open Request
  Opened --> InProgress: PSSM employee starts reviewing it
  InProgress --> Fulfilled: TempEmployee\nAgrees
  InProgress --> NotPossible: TempEmployee\nNot Found
  Fulfilled --> Closed : Contract Manager \ncloses Request
  NotPossible --> Closed : Contract Manager \ncloses Request
  Closed --> [*]
}

@enduml
