@startuml
skinparam monochrome true
'left to right direction
title "PSSM"\nUse Case Diagram

rectangle "staff fullfilment system" as S {
    (Fulfill staffing request) as FFSR
    (Open staffing request) as OSR
    (Place staff members) as PSM
    (Fill staffing request) as FSR
}
FFSR ..> OSR : <<include>>
FFSR ..> PSM : <<include>>
FFSR ..> FSR : <<include>>

:Contract \nManager: as CM
:Client: as C
:PSSM Employee: as PSSM
:Temporary Employee: as TE

C - FFSR
C - FSR
OSR - C
OSR - CM
PSM - PSSM
PSSM - FSR
TE - FSR
@enduml
