@startuml
skinparam monochrome true
title PSSM\nTemporary Staff Fullfilment System\nActivity Diagram

start
  :receive staffing demand;
note left
  TRIGGER: from Client
end note
:check contract;
note left
  Not expired
  Position covered
  Fee falls in range
end note
if (demand is valid?) then (yes)
  :Open an outstanding
  Staffing Request;
  while (   employee\nsearch active?) is (yes)
    :check employee database
    for suitable candidate;
    note right
      Type of staff
      Experience
      Qualifications
    end note
    if (is found?) then (yes)
      :mark candidate
      "reserved";
      :contact candidate;
      if (placement agreed?) then (yes)
        :mark candidate
        "placed";
        :send Staffing
        Request and Bill
        to Client;
      else (no)
          :unmark candidate
          "reserved";
          note right
            Keep looking
            for prospective Employee
          end note
      endif
    else (no)
      :create UTF memo;
    endif
  endwhile (no)
else (no)
  :return Staffing Request
  with Why Letter to Client;
  :file Why Letter
  with Contract office;
  end
endif
:send document
copies to Contract
Manager;
note left
  Staffing Request
  UTF Memo (if any)
  Bill
end note
if (is demand met?)
  :Close open
  Staffing Request;
else
  :notify Client;
endif
:file paperwork
in Contract office;
note left
  Staffing Request
  UTF Memo
  Bill
end note
stop

@enduml
