@startuml
skinparam monochrome true
title PSSM Temporary Staff Fullfilment\nActivity Diagram

start
  :Receive Staffing Request;
note left
  TRIGGER: From Client
end note
:Check Contract;
note left
  Not expired
  Position covered
  Fee falls in range
end note
if (is valid?) then (yes)
  :Create outstanding
  Staffing Request;
  while (   Employee\nsearch active?) is (yes)
    :Check for qualified Employee;
    note right
      Type of Staff
      Experience
      Qualifications
    end note
    if (is found?) then (yes)
      :Mark as reserved;
      :Contact prospective
      Employee;
      if (agreed?) then(yes)
        :Mark as placed;
        :Send
        Request and Bill
        to Client;
      else (no)
          :Unmark
          reserved;
          note right
            Keep looking
            for prospective Employee
          end note
      endif
    else (no)
      :Create UTF Memo;
    endif
  endwhile (no)
else (no)
  :Return Staffing Request\nwith Why Letter;
  :File Why Letter;
  end
endif
:check papers;
note left
  Staffing Request
  UTF Memo(if any)
  Bill
end note
if (is request fill?)
  :Close open
  Staffing request;
else
  :Notify client;
endif
:File papers;
stop

@enduml
