@startuml
skinparam monochrome true
'left to right direction
title PSSM\nUse Case Diagram

rectangle "Temporary Staff Fullfilment System" as S {
    (Fulfill\n Staffing Request) as FFSR
    (Open\n Staffing Request) as OSR
    (Place\n Staff Members) as PSM
    (Fill\n Staffing Request) as FSR
}
FFSR ..> OSR : <<include>>
FFSR ..> PSM : <<include>>
FFSR ..> FSR : <<include>>

:Contract Manager\n: as CM
:Client\n: as C
:PSSM Employee\n: as PE
:Temporary Employee\n: as TE

FSR -down- TE
OSR -down- CM
FFSR - C
OSR - C
PSM - PE
FSR - PE

@enduml
